title: Ultimate GPU Culling System (UGCS)
description: A GPU-based occlusion culling system for Unity that drastically improves performance with almost zero configuration.
theme: just-the-docs
color_scheme: dark

url: https://afterburnerunity.github.io/UltimateGPUCullingSystem/

aux_links:
  Unity Asset Store: https://assetstore.unity.com
